id = "asqi"
aliases = ["asqi", "auto-save-interval", "auto-save-queue-interval"]
admin = true
title = "Timeing adjustment - Auto-save queue interval"
description = """
<c yellow>'asqi'</c> alters the auto-save queue's execution interval in real-time without
restart and/or configuration changes.

<c green>Usage:</c> asqi <c cyan>INTERVAL</c>

<c red>NOTE:</c>
  <c gray>*</c> <c blue>[<c cyan>INTERVAL</c>]</c> is in seconds.
"""