id = "bc"
aliases = ["bc", "builder chat", "bchat"]
title = "Builders' chatter…"
builder = true
description = """
<c yellow>'bc'</c> posts a message onto builders-only channel, which admins, naturally, can
read too just the same.

<c green>Usage:</c> bc <c cyan>TEXT</c>
"""
