id = "channels-opt"
aliases = ["opt-in", "opt-out"]
title = "Communication is the key …"
description = """
To opt in/out:

       channels in <c cyan>CHANNEL</c>
       channels out <c cyan>CHANNEL</c>
"""
