id = "channels"
aliases = ["channels", "comms", "communication"]
title = "Communication is the key …"
description = """
'channels' command lists all the available channels.  It can also be used
to opt-in and opt-out from some of them, while some channels are by their
nature "always on".

Some examples of opt-in CHANNEL include, but are not limited to:
  <c gray>*</c> Newbie     -- a channel for all sorts of newcomer issues.
  <c gray>*</c> OOC        -- generic Out-Of-Character chatter.
  <c gray>*</c> QA         -- Questions & Answers. But do leave OOC questions for OOC…

<c green>Usage:</c> channels
       channels in <c cyan>CHANNEL</c>
       channels out <c cyan>CHANNEL</c>
"""