id = "dir"
aliases = ["dir", "direction",
           "north", "south", "west", "east",
           "northwest", "northeast", "southwest", "southeast",
           "up", "down"]
title = "Directions, directions!"
description = """
Going to/looking at various directions involves one or the other of the
following values:

  <c gray>*</c> north, south, east, west
  <c gray>*</c> northeast, northwest, southeast, southwest
  <c gray>*</c> up, down

Situationally other "directions" might be available, e.g.:

  <c gray>*</c> door, portal, gate, window, trapdoor, etc. …
"""
