id = "dmg"
title = "Causes/repairs damage…"
aliases = ["dmg", "fix"]
admin = true
description = """
<c yellow>'dmg' is used to cause/repair any physical damage present on any target creature.

<c green>Usage: </c>dmg <c cyan>TARGET AMOUNT</c>
       dmg fix <c cyan>TARGET AMOUNT</c>

<c red>NOTE:</c>
  <c gray>*</c> AMOUNT is a percentage value.
"""
