id = "force"
aliases = ["force", "force all"]
admin = true
title = "Use the Force, Dave…"
description = """
<c yellow>'force'</c> is used to force someone or something to do something.

<c green>Usage:</c> force <c blue>[-]</c> <c cyan>TARGET COMMAND <c blue>[ARGS]</c></c>
       force all <c blue>[-]</c> <c cyan>COMMAND <c blue>[ARGS]</c></c>

<c red>NOTE:</c>
  <c blue>*</c> <c blue>[<c cyan>-</c>]</c> flag posts the COMMAND anonymously.
    To be used internally by e.g. scripts or spells, etc.
<c red>---</c>
<c cyan>"With great power comes great responsibility"</c>, and therefore, this command
is to be used sparingly, if ever at all.
"""
