id = "goto"
title = "Goes to places…"
aliases = [
    "goto",
    "go",
    "move to",
]
description = """
<c yellow>'goto'</c> is used to go to e.g. various directions, like:

    North, East, South, West,
    NorthEast, NorthWest, SouthEast, SouthWest,
    Up, and Down.

<c green>Usage:</c> goto <c cyan>[DIRECTION]</c>
"""
admin = false
builder = false
