id = "hedit-internal-commands"
title = "HEdit - commanding the tools..."
aliases = ["hedit-internal-commands"]
description = """
Internal commands of <c cyan>HEdit</c>:

  <c blue>*</c> admin
  <c blue>*</c> alias
  <c blue>*</c> builder
  <c blue>*</c> data
  <c blue>*</c> desc
  <c blue>*</c> save
  <c blue>*</c> title

Each of the commands has their usage info available with <c yellow>'?'</c>, like:
    <c yellow>alias ?</c>
"""
admin = false
builder = false
