id = "say"
aliases = ["say", "speak"]
title = "If you have something to say, <c yellow>'say'</c> it…"
description = """
<c yellow>'say'</c> command, with some sentence(s) following it, posts the given text for
all in the same room to see.

If given text ends with an exclamation mark you will instead of "saying"
"exclaim" instead.  Akin to exclaims, statements that end with a question mark
are converted into <c yellow>'ask'</c> questions.

<c green>Usage:</c> say <c cyan>TEXT</c>

<c green>See:</c> <c blue>[<c cyan>ask</c>]</c>
"""
