id = "translocate"
aliases = ["translocate", "teleport"]
admin = true
title = "Transporting people ..."
description = """
<c yellow>'translocate'</c> is used to transport a player (self or otherwise) to another
(existing) location in the world.  The command, obviously, fails if target
location does not exist.

<c green>Usage:</c> translocate <c cyan>TARGET</c> <c cyan>ROOM-ID</c>
"""
